pipeline:
  build:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - npm install

  publish api:
    image: plugins/gcr
    repo: swift-synthesis-194400/maily-api
    secrets: [google_credentials]
    tags: latest
    when:
      branch: master
      event: push

  publish postgres:
    image: plugins/gcr
    repo: swift-synthesis-194400/maily-postgres
    dockerfile: docker/postgres.dockerfile
    secrets: [google_credentials]
    tags: latest
    when:
      branch: master
      event: push
    
  deploy: 
    image: nytimes/drone-gke:0.7
    zone: us-central1-c
    cluster: maily-cluster
    namespace: ${DRONE_BRANCH}
    secrets:
    - source: google_credentials
      target: token
    - source: postgres_password
      target: pg_password 
    vars:
      app_image: gcr.io/swift-synthesis-194400/maily-api:latest
      postgres_image: gcr.io/swift-synthesis-194400/maily-postgres:latest
      postgres_password: $PG_PASSWORD
      app: maily-api
    when:
      branch: master
      event: push
  


