pipeline:
  build:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - npm install

  publish:
    image: plugins/gcr
    repo: swift-synthesis-194400/maily-api
    tags: latest
    secrets: [google_credentials]

  deploy: 
    image: nytimes/drone-gke:0.7
    zone: us-central1-c
    cluster: maily-cluster
    namespace: ${DRONE_BRANCH}
    secrets:
    - source: google_credentials
      target: token
    vars:
      image: gcr.io/swift-synthesis-194400/maily-api:latest
      app: maily-api


