pipeline:
  build:
    image: node:8.6.0
    commands:
      - node -v
      - npm -v
      - npm install

  publish api:
    image: plugins/gcr
    repo: swift-synthesis-194400/maily-api
    secrets: [google_credentials]
    tags: ${DRONE_COMMIT}
    when:
      branch: master
      event: push

  publish postgres:
    image: plugins/gcr
    repo: swift-synthesis-194400/maily-postgres
    dockerfile: docker/postgres.dockerfile
    secrets: [google_credentials]
    tags: ${DRONE_COMMIT}
    when:
      branch: master
      event: push
          
  deploy: 
    image: nytimes/drone-gke:0.7
    zone: us-central1-c
    cluster: maily-cluster
    namespace: ${DRONE_BRANCH}
    secrets:
    - source: google_credentials
      target: token
    vars:
      app_image: gcr.io/swift-synthesis-194400/maily-api:${DRONE_COMMIT}
      postgres_image: gcr.io/swift-synthesis-194400/maily-postgres:${DRONE_COMMIT}
      postgres_password: postgres
      app: maily-api
    when:
      branch: master
      event: push

  


