kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: {{.app}}

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.app}}
    spec:
      containers:
        - name: app
          image: {{.image}}
          ports:
            - containerPort: 8000

---
kind: Service
apiVersion: v1

metadata:
  name: {{.app}}

spec:
  type: LoadBalancer
  selector:
    app: {{.app}}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP