version: '3.1'

services:

  postgres:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
       - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  maily-api:
    build:
      context: .
      dockerfile: Dockerfile 
    image: mtgao/maily-api
    environment:
        PGHOST: postgres
        PGUSER: postgres 
        PGPASSWORD: postgres
    restart: always
    ports:
      - 8000:8000
    links: 
      - postgres 
